/* CVS $Id: $ */
package org.example.test; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from file:C:\Users\shane.AXIOM\git\schemagen-maven\src\it\schemagen-integration-2\src/main/vocabs/test1.ttl 
 * @author Auto-generated by schemagen on 11 Sep 2012 16:38 
 */
public class Test1 {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://example.org/test#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource Cls = m_model.createResource( "http://example.org/test#Cls" );
    
}
